### ISSUE TITLE
Would be great to recommend an article to follow

### ISSUE THREAD

**Issue by LW1113223** [psrobotics/quadruped_walk_mpc_ctr#2]
Hi, is there any article to recommend to better understand your MPC code

**Comment by psrobotics** [comment]
You can check these papers, 
[https://arxiv.org/abs/1909.06586](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbjlSSzBBMHZscDFSOWlVOFNROFpYZWczblRPZ3xBQ3Jtc0tuWHBPcGVITGZWSDFDVk1zcy1fdjdITkFyVkJCanhGQjI0NnljQTFxbi1SdWJIX281V2NrSm1mR3Z2dGd6UVJKeXZHcFdWcHlCd0lnNGFuVHV2a2FCdlMwMzltOFdMZktTaTNIYkNmRnoxcWc5QnU2dw&q=https%3A%2F%2Farxiv.org%2Fabs%2F1909.06586&stzid=UgxDzE3WiqUxeuf3Yk14AaABAg.9pJRz8K1s3a9pL9ElnAE79), [https://ieeexplore.ieee.org/document/9555775](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqa3A4blpSM1hYV1dLTkFfTTRjMzJjMzlUOGpFd3xBQ3Jtc0tuY0lLdng1MGxnVmUxMW55QW5zWVRKSUU1dFlraXRZYjBMNVp2NFJSRUJ5b0E1SU5vVXFWOFBIN1FDWHdKZDk2MGZCb2Y5UGJNbFV6bWkzaktKaWpiVF9YYVNnUExwZ0MxZkpoaGs3aUNfTV9Qd1Etbw&q=https%3A%2F%2Fieeexplore.ieee.org%2Fdocument%2F9555775&stzid=UgxDzE3WiqUxeuf3Yk14AaABAg.9pJRz8K1s3a9pL9ElnAE79), [https://arxiv.org/abs/2104.09025](https://www.youtube.com/redirect?event=comments&redir_token=QUFFLUhqbE94U2FfMWJTanRMM3BNMjl1T00zRTRzVDU0Z3xBQ3Jtc0trWVdZUWV1VnNPaTQ2R2RmU0YzeGstX0V3VG1QYkJxY005S3FHNU1zTzUwUkdvOHJibHFTNDF3aXlWbE0xbUF0N3Z2b0lDTFFxQ3FCdXZvOHEzSWJBYlJhUk83ZnRtdUNXekFldldsWGdxeEVDcFlmSQ&q=https%3A%2F%2Farxiv.org%2Fabs%2F2104.09025&stzid=UgxDzE3WiqUxeuf3Yk14AaABAg.9pJRz8K1s3a9pL9ElnAE79)
